-- Table structure for oneday_trips
CREATE TABLE IF NOT EXISTS `oneday_trips` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title_th` varchar(255) NOT NULL,
  `title_en` varchar(255) NOT NULL,
  `description_th` text DEFAULT NULL,
  `description_en` text DEFAULT NULL,
  `location_th` varchar(255) DEFAULT NULL,
  `location_en` varchar(255) DEFAULT NULL,
  `province_key` varchar(50) NOT NULL DEFAULT 'phuket' COMMENT 'Province key for filtering',
  `duration_th` varchar(100) DEFAULT NULL COMMENT 'e.g. ทั้งวัน, ครึ่งวัน',
  `duration_en` varchar(100) DEFAULT NULL COMMENT 'e.g. Full Day, Half Day',
  `price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `discount_price` decimal(10,2) DEFAULT NULL COMMENT 'Original price before discount',
  `image` varchar(500) DEFAULT NULL,
  `gallery` JSON DEFAULT NULL COMMENT 'Array of image URLs',
  `rating` decimal(2,1) DEFAULT 4.5,
  `reviews` int(11) DEFAULT 0,
  `bestseller` tinyint(1) DEFAULT 0,
  `tags_th` JSON DEFAULT NULL COMMENT 'Array of tags in Thai',
  `tags_en` JSON DEFAULT NULL COMMENT 'Array of tags in English',
  `highlights_th` JSON DEFAULT NULL COMMENT 'Array of highlights in Thai',
  `highlights_en` JSON DEFAULT NULL COMMENT 'Array of highlights in English',
  `itinerary` JSON DEFAULT NULL COMMENT 'Array of {time, title_th, title_en, description_th, description_en}',
  `included_th` JSON DEFAULT NULL COMMENT 'What is included (Thai)',
  `included_en` JSON DEFAULT NULL COMMENT 'What is included (English)',
  `excluded_th` JSON DEFAULT NULL COMMENT 'What is not included (Thai)',
  `excluded_en` JSON DEFAULT NULL COMMENT 'What is not included (English)',
  `meeting_point_th` varchar(500) DEFAULT NULL,
  `meeting_point_en` varchar(500) DEFAULT NULL,
  `important_info_th` text DEFAULT NULL,
  `important_info_en` text DEFAULT NULL,
  `sort_order` int(11) NOT NULL DEFAULT 0,
  `status` enum('active','inactive') DEFAULT 'active',
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_province` (`province_key`),
  KEY `idx_bestseller` (`bestseller`),
  KEY `idx_sort_order` (`sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert sample data
INSERT INTO `oneday_trips` (
  `title_th`, `title_en`,
  `description_th`, `description_en`,
  `location_th`, `location_en`,
  `province_key`, `duration_th`, `duration_en`,
  `price`, `discount_price`, `image`,
  `rating`, `reviews`, `bestseller`,
  `tags_th`, `tags_en`,
  `highlights_th`, `highlights_en`,
  `itinerary`,
  `included_th`, `included_en`,
  `excluded_th`, `excluded_en`,
  `sort_order`, `status`
) VALUES
(
  'ทัวร์เกาะพีพี และอ่าวมาหยา เรือสปีดโบ๊ท',
  'Phi Phi Island & Maya Bay Speedboat Tour',
  'สัมผัสประสบการณ์สุดพิเศษ ล่องเรือสปีดโบ๊ทชมความงดงามของหมู่เกาะพีพี อ่าวมาหยาที่โด่งดัง และดำน้ำดูปะการังน้ำใส',
  'Experience an unforgettable speedboat journey to the stunning Phi Phi Islands, visit the famous Maya Bay, and enjoy snorkeling in crystal clear waters.',
  'ภูเก็ต, ประเทศไทย',
  'Phuket, Thailand',
  'phuket',
  'ทั้งวัน (8-9 ชม.)',
  'Full Day (8-9 hours)',
  2490,
  3500,
  'https://images.unsplash.com/photo-1598895015795-c49c55b5d141?q=80&w=1000&auto=format&fit=crop',
  4.9,
  856,
  1,
  '["เรือสปีดโบ๊ท", "ดำน้ำตื้น", "อาหารกลางวัน", "รับส่งฟรี"]',
  '["Speedboat", "Snorkeling", "Lunch Included", "Free Pickup"]',
  '["ชมอ่าวมาหยาที่โด่งดังจากภาพยนตร์ The Beach", "ดำน้ำชมปะการังที่เกาะไผ่", "เที่ยวชมถ้ำไวกิ้งและอ่าวปิเละ", "พักผ่อนบนหาดทรายขาว"]',
  '["Visit the famous Maya Bay from The Beach movie", "Snorkeling at Bamboo Island", "Explore Viking Cave and Pileh Lagoon", "Relax on white sandy beaches"]',
  '[{"time":"07:30","title_th":"รับจากโรงแรม","title_en":"Hotel Pickup","description_th":"รถตู้ปรับอากาศรับจากโรงแรมในภูเก็ต","description_en":"Air-conditioned van pickup from your hotel in Phuket"},{"time":"08:30","title_th":"ออกเดินทางจากท่าเรือ","title_en":"Departure from Pier","description_th":"ขึ้นเรือสปีดโบ๊ทที่ท่าเรือรัษฎา","description_en":"Board speedboat at Rassada Pier"},{"time":"09:30","title_th":"เกาะไผ่","title_en":"Bamboo Island","description_th":"ดำน้ำดูปะการังและพักผ่อนบนชายหาด","description_en":"Snorkeling and beach relaxation"},{"time":"11:00","title_th":"อ่าวมาหยา","title_en":"Maya Bay","description_th":"ชมอ่าวมาหยาที่โด่งดัง ถ่ายรูปและเดินชายหาด","description_en":"Visit the famous Maya Bay, photo opportunities"},{"time":"12:30","title_th":"อาหารกลางวัน","title_en":"Lunch","description_th":"อาหารบุฟเฟ่ต์ที่เกาะพีพีดอน","description_en":"Buffet lunch at Phi Phi Don"},{"time":"14:00","title_th":"อ่าวปิเละ & ถ้ำไวกิ้ง","title_en":"Pileh Lagoon & Viking Cave","description_th":"ชมความงามของอ่าวปิเละและถ้ำไวกิ้ง","description_en":"Explore Pileh Lagoon and Viking Cave"},{"time":"15:30","title_th":"เดินทางกลับ","title_en":"Return Journey","description_th":"เรือออกเดินทางกลับภูเก็ต","description_en":"Speedboat departs back to Phuket"},{"time":"17:00","title_th":"ถึงภูเก็ต","title_en":"Arrive Phuket","description_th":"ส่งกลับโรงแรม","description_en":"Transfer back to hotel"}]',
  '["รถรับส่งจากโรงแรม", "เรือสปีดโบ๊ท", "อุปกรณ์ดำน้ำตื้น", "อาหารกลางวัน + เครื่องดื่ม", "ค่าธรรมเนียมอุทยาน", "ประกันการเดินทาง", "ไกด์พูดไทย/อังกฤษ"]',
  '["Hotel pickup and drop-off", "Speedboat transportation", "Snorkeling equipment", "Lunch + drinks", "National park fees", "Travel insurance", "Thai/English guide"]',
  '["ค่าใช้จ่ายส่วนตัว", "ทิปไกด์และคนขับ", "เครื่องดื่มแอลกอฮอล์"]',
  '["Personal expenses", "Tips for guide and driver", "Alcoholic beverages"]',
  1,
  'active'
),
(
  'ทัวร์ 4 เกาะกระบี่',
  '4 Islands Krabi Tour',
  'เที่ยวครบ 4 เกาะสวย ทะเลแหวก เกาะไก่ เกาะทับ เกาะปอดะ ดำน้ำดูปะการัง พร้อมอาหารกลางวัน',
  'Visit 4 beautiful islands: Tub Island, Chicken Island, Poda Island, and the famous Separated Sea. Snorkeling included with lunch.',
  'กระบี่, ประเทศไทย',
  'Krabi, Thailand',
  'krabi',
  'ทั้งวัน (7-8 ชม.)',
  'Full Day (7-8 hours)',
  990,
  1500,
  'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?q=80&w=1000&auto=format&fit=crop',
  4.8,
  1120,
  1,
  '["เรือหางยาว", "ทะเลแหวก", "ดำน้ำตื้น", "อาหารกลางวัน"]',
  '["Longtail Boat", "Separated Sea", "Snorkeling", "Lunch"]',
  '["เดินบนทะเลแหวก ปรากฏการณ์ธรรมชาติสุดมหัศจรรย์", "ถ่ายรูปกับเกาะไก่รูปทรงแปลกตา", "ดำน้ำดูปะการังที่เกาะปอดะ", "พักผ่อนบนหาดทรายขาวละเอียด"]',
  '["Walk on the amazing Separated Sea natural phenomenon", "Photo with unique Chicken Island rock formation", "Snorkeling at Poda Island coral reef", "Relax on fine white sandy beach"]',
  '[{"time":"08:00","title_th":"รับจากที่พัก","title_en":"Hotel Pickup","description_th":"รถตู้รับจากที่พักในกระบี่","description_en":"Van pickup from Krabi hotel"},{"time":"09:00","title_th":"ออกเดินทาง","title_en":"Departure","description_th":"ขึ้นเรือหางยาวที่อ่าวนาง","description_en":"Board longtail boat at Ao Nang"},{"time":"09:30","title_th":"เกาะทับ - ทะเลแหวก","title_en":"Tub Island - Separated Sea","description_th":"เดินบนทะเลแหวก เชื่อมเกาะทับและเกาะไก่","description_en":"Walk on Separated Sea connecting Tub and Chicken Island"},{"time":"11:00","title_th":"เกาะปอดะ","title_en":"Poda Island","description_th":"ดำน้ำดูปะการังและพักผ่อนบนหาด","description_en":"Snorkeling and beach relaxation"},{"time":"12:30","title_th":"อาหารกลางวัน","title_en":"Lunch","description_th":"อาหารกล่องบนเกาะ","description_en":"Lunch box on the island"},{"time":"14:00","title_th":"เกาะไก่","title_en":"Chicken Island","description_th":"ถ่ายรูปและว่ายน้ำรอบเกาะ","description_en":"Photo and swimming around the island"},{"time":"15:30","title_th":"เดินทางกลับ","title_en":"Return","description_th":"เรือกลับอ่าวนาง","description_en":"Boat returns to Ao Nang"},{"time":"16:30","title_th":"ส่งกลับที่พัก","title_en":"Hotel Drop-off","description_th":"รถตู้ส่งกลับที่พัก","description_en":"Van transfer back to hotel"}]',
  '["รถรับส่งจากที่พัก", "เรือหางยาว", "อุปกรณ์ดำน้ำตื้น", "อาหารกลางวัน + น้ำดื่ม", "ค่าธรรมเนียมอุทยาน", "ประกันการเดินทาง"]',
  '["Hotel pickup and drop-off", "Longtail boat", "Snorkeling equipment", "Lunch + drinking water", "National park fees", "Travel insurance"]',
  '["ค่าใช้จ่ายส่วนตัว", "ทิปไกด์", "เครื่องดื่มเพิ่มเติม"]',
  '["Personal expenses", "Guide tips", "Additional drinks"]',
  2,
  'active'
),
(
  'ทัวร์อยุธยา เมืองมรดกโลก',
  'Ayutthaya World Heritage Tour',
  'เยือนอดีตราชธานีเก่าแก่ ชมวัดและโบราณสถานที่ได้รับการขึ้นทะเบียนเป็นมรดกโลก',
  'Visit the ancient capital and UNESCO World Heritage Site. Explore historic temples and ruins.',
  'พระนครศรีอยุธยา, ประเทศไทย',
  'Ayutthaya, Thailand',
  'ayutthaya',
  'ทั้งวัน (9-10 ชม.)',
  'Full Day (9-10 hours)',
  890,
  1290,
  'https://images.unsplash.com/photo-1528181304800-259b08848526?q=80&w=1000&auto=format&fit=crop',
  4.7,
  342,
  0,
  '["มรดกโลก", "ประวัติศาสตร์", "วัดเก่าแก่", "รถตู้ปรับอากาศ"]',
  '["UNESCO Heritage", "Historical", "Ancient Temples", "AC Van"]',
  '["ชมวัดมหาธาตุ เศียรพระในรากไม้", "เยือนวัดใหญ่ชัยมงคล เจดีย์ยักษ์", "ชมพระราชวังบางปะอิน สถาปัตยกรรมผสมผสาน", "ล่องเรือชมวิถีชีวิตริมน้ำ"]',
  '["See Wat Mahathat Buddha head in tree roots", "Visit Wat Yai Chai Mongkol giant pagoda", "Explore Bang Pa-In Palace mixed architecture", "Boat cruise along the river"]',
  '[{"time":"07:00","title_th":"รับจากกรุงเทพ","title_en":"Bangkok Pickup","description_th":"รถตู้ปรับอากาศรับจากโรงแรม","description_en":"AC van pickup from Bangkok hotel"},{"time":"09:00","title_th":"วัดมหาธาตุ","title_en":"Wat Mahathat","description_th":"ชมเศียรพระพุทธรูปในรากต้นโพธิ์","description_en":"See Buddha head entwined in tree roots"},{"time":"10:30","title_th":"วัดพระศรีสรรเพชญ์","title_en":"Wat Phra Si Sanphet","description_th":"เจดีย์ 3 องค์ เคยเป็นวัดในพระราชวัง","description_en":"Three pagodas, former royal temple"},{"time":"12:00","title_th":"อาหารกลางวัน","title_en":"Lunch","description_th":"อาหารไทยท้องถิ่น","description_en":"Local Thai lunch"},{"time":"13:30","title_th":"วัดใหญ่ชัยมงคล","title_en":"Wat Yai Chai Mongkol","description_th":"พระเจดีย์องค์ใหญ่และพระพุทธไสยาสน์","description_en":"Large pagoda and reclining Buddha"},{"time":"15:00","title_th":"พระราชวังบางปะอิน","title_en":"Bang Pa-In Palace","description_th":"พระราชวังฤดูร้อนอันงดงาม","description_en":"Beautiful summer palace"},{"time":"17:00","title_th":"เดินทางกลับ","title_en":"Return Journey","description_th":"ออกเดินทางกลับกรุงเทพ","description_en":"Depart back to Bangkok"},{"time":"19:00","title_th":"ถึงกรุงเทพ","title_en":"Arrive Bangkok","description_th":"ส่งกลับโรงแรม","description_en":"Hotel drop-off"}]',
  '["รถตู้ปรับอากาศ", "อาหารกลางวัน", "ค่าเข้าชมสถานที่", "น้ำดื่ม", "ไกด์ท้องถิ่น", "ประกันการเดินทาง"]',
  '["Air-conditioned van", "Lunch", "Entrance fees", "Drinking water", "Local guide", "Travel insurance"]',
  '["ค่าใช้จ่ายส่วนตัว", "ทิปไกด์", "เครื่องดื่มเพิ่มเติม"]',
  '["Personal expenses", "Guide tips", "Additional drinks"]',
  3,
  'active'
);
